<?php
$gameinfos = [
  'designer' => 'Emiliano Sciarra',
  'artist' => 'Alex Pierangelini',
  'year' => 2002,
  'publisher' => 'DV Giochi',
  'publisher_website' => 'https://www.dvgiochi.com/',
  'publisher_bgg_id' => 917,
  'bgg_id' => 3955,
  'players' => [4,5,6,7],
  'suggest_player_number' => 5,
  'not_recommend_player_number' => NULL,
  'estimated_duration' => 30,
  'fast_additional_time' => 30,
  'medium_additional_time' => 40,
  'slow_additional_time' => 50,
  'tie_breaker_description' => '',
  'is_beta' => 1,
  'is_coop' => 0,
  'complexity' => 3,
  'luck' => 3,
  'strategy' => 3,
  'diplomacy' => 3,
  'player_colors' => ['ff0000', '008000', '0000ff', 'ffa500', '773300'],
  'favorite_colors_support' => true,
  'game_interface_width' => [
    'min' => 740,
    'max' => NULL,
  ],
  'tags' =>  [2],
  'is_sandbox' => false,
  'turnControl' => 'simple',
];
?>
